name: PHPUnit
on:
  push:
    branches:
      - master
    tags:
      - v*.*.*
  pull_request:
    branches:
      - master

jobs:
  Build:
    runs-on: 'ubuntu-latest'
    container: 'byjg/php:${{ matrix.php-version }}-cli'
    strategy:
      matrix:
        php-version:
          - "8.0"
          - "7.4"
#          - "7.3"
#          - "7.2"
#          - "7.1"
#          - "7.0"
#          - "5.6"

    steps:
      - uses: actions/checkout@v2
      - run: |
          composer install
          ./vendor/bin/phpunit